# Generated by Django 4.1.2 on 2022-10-30 13:27

import ai_rest.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_rest", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="predictimage",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="predictimage",
            name="image",
            field=models.ImageField(upload_to=ai_rest.models.image_upload_to),
        ),
    ]
